import faker from "faker";
import {
    generateAnimalPictureVaried,
    generateAnimalPictureVariedWithId,
    generateDate13DaysAgo,
    generateDate21DaysAgo,
    generateDateEightDaysAgo,
    generateDateFiveDaysAgo,
    generateDateOneDayAgo,
    generateDateThreeDaysAgo,
    generateDateTwoDaysAgo,
    generateDbSerialId,
    generateFishingEvent,
    generateFiveStarRating,
    generateFutureDate13Days,
    generateFutureDate21Days,
    generateFutureDateEightDays,
    generateFutureDateFiveDays,
    generateFutureDateOneDay,
    generateFutureDateThreeDays,
    generateFutureDateTwoDays,
    generateHuntingEvent,
    generateNaturePictureVaried,
    generateNaturePictureVariedWithId,
    generateNumberBetween1and10,
    generateOutdoorEvent,
    generateOutdoorPictureVariedWithId,
    generatePastDate,
    generatePersonPictureVaried,
    generatePersonPictureVariedWithId,
    generatePhoneNumber
} from "./generators/index.js";

export const FieldTags = Object.freeze({
    //geo
    city: "city",
    state: "state",
    zipCode: "zipCode",
    addressLine1: "addressLine1",
    addressLine2: "addressLine2",
    longitude: "longitude",
    latitude: "latitude",
    // personal
    birthday: "birthday",
    firstName: "firstName",
    lastName: "lastName",
    email: "email",
    serialId: "serialId",
    pastDate: "pastDate",
    company: "company",
    phoneNumber: "phoneNumber",
    fiveStarRating: "fiveStarRating",
    // media
    imageAnimals: "imageAnimals",
    imagePerson: "imagePerson",
    imageNature: "imageNature",
    imageAnimalsWithId: "imageAnimalsWithId",
    imagePersonWithId: "imagePersonWithId",
    imageNatureWithId: "imageNatureWithId",
    imageOutdoorWithId: "imageOutdoorWithId",
    // text
    loremSentence: "loremSentence",
    loremParagraph: "loremParagraph",
    loremParagraphs: "loremParagraphs",
    productDescription: "productDescription",
    huntingEventTitle: "huntingEventTitle",
    fishingEventTitle: "fishingEventTitle",
    outdoorEventTitle: "outdoorEventTitle",
    // numbers
    between1and10: "between1and10",
    price: "price",
    // time
    pastDate1Day: "pastDate1Day",
    pastDate2Days: "pastDate2Days",
    pastDate3Days: "pastDate3Days",
    pastDate5Days: "pastDate5Days",
    pastDate8Days: "pastDate8Days",
    pastDate13Days: "pastDate13Days",
    pastDate21Days: "pastDate21Days",
    futureDate1Day: "futureDate1Day",
    futureDate2Days: "futureDate2Days",
    futureDate3Days: "futureDate3Days",
    futureDate5Days: "futureDate5Days",
    futureDate8Days: "futureDate8Days",
    futureDate13Days: "futureDate13Days",
    futureDate21Days: "futureDate21Days",
})

export const fieldFakerMap = Object.freeze({
    // geo
    [FieldTags.city]:  faker.address.city,
    [FieldTags.state]:  faker.address.state,
    [FieldTags.zipCode]:  faker.address.zipCode,
    [FieldTags.addressLine1]:  faker.address.streetAddress,
    [FieldTags.addressLine2]: faker.address.secondaryAddress,
    [FieldTags.longitude]: faker.address.longitude,
    [FieldTags.latitude]: faker.address.latitude,
    //
    [FieldTags.birthday]: faker.date.past,
    [FieldTags.firstName]: faker.name.firstName,
    [FieldTags.lastName]: faker.name.lastName,
    [FieldTags.email]: faker.internet.email,
    [FieldTags.serialId]: generateDbSerialId,
    [FieldTags.company]: faker.company.companyName,
    [FieldTags.phoneNumber]: generatePhoneNumber,
    [FieldTags.fiveStarRating]: generateFiveStarRating,
    // media
    [FieldTags.imageOutdoorWithId]: generateOutdoorPictureVariedWithId,
    [FieldTags.imageAnimalsWithId]: generateAnimalPictureVariedWithId,
    [FieldTags.imagePersonWithId]: generatePersonPictureVariedWithId,
    [FieldTags.imageNatureWithId]: generateNaturePictureVariedWithId,
    [FieldTags.imageAnimals]: generateAnimalPictureVaried,
    [FieldTags.imagePerson]: generatePersonPictureVaried,
    [FieldTags.imageNature]: generateNaturePictureVaried,
    // text
    [FieldTags.loremSentence]: faker.lorem.sentence,
    [FieldTags.loremParagraph]: faker.lorem.paragraph,
    [FieldTags.loremParagraphs]: faker.lorem.paragraphs,
    [FieldTags.productDescription]: faker.commerce.productDescription,
    [FieldTags.huntingEventTitle]: generateHuntingEvent,
    [FieldTags.fishingEventTitle]: generateFishingEvent,
    [FieldTags.outdoorEventTitle]: generateOutdoorEvent,

    // numbers
    [FieldTags.between1and10]: generateNumberBetween1and10,
    [FieldTags.price]: faker.commerce.price,

    // time
    [FieldTags.pastDate]: generatePastDate,
    [FieldTags.pastDate1Day]: generateDateOneDayAgo,
    [FieldTags.pastDate2Days]: generateDateTwoDaysAgo,
    [FieldTags.pastDate3Days]: generateDateThreeDaysAgo,
    [FieldTags.pastDate5Days]: generateDateFiveDaysAgo,
    [FieldTags.pastDate8Days]: generateDateEightDaysAgo,
    [FieldTags.pastDate13Days]: generateDate13DaysAgo,
    [FieldTags.pastDate21Days]: generateDate21DaysAgo,
    [FieldTags.futureDate1Day]: generateFutureDateOneDay,
    [FieldTags.futureDate2Days]: generateFutureDateTwoDays,
    [FieldTags.futureDate3Days]: generateFutureDateThreeDays,
    [FieldTags.futureDate5Days]: generateFutureDateFiveDays,
    [FieldTags.futureDate8Days]: generateFutureDateEightDays,
    [FieldTags.futureDate13Days]: generateFutureDate13Days,
    [FieldTags.futureDate21Days]: generateFutureDate21Days,

});
